var app = angular.module('app', ["ngTouch", "angucomplete-alt"]);

app.controller('MainController', ['$scope', '$http',
    function MainController($scope, $http) {
        $scope.remoteUrlRequestFn = function (str) {
            return {q: str};
        };

        $scope.locations = [
            {settlement:"אבו גווייעד",council:" "},
            {settlement:"אבו גוש",council:" "},
            {settlement:"אבו סנאן",council:"מטה אשר"},
            {settlement:"אבו סריחאן",council:" "},
            {settlement:"אבו עבדון",council:" "},
            {settlement:"אבו עמאר",council:" "},
            {settlement:"אבו עמרה",council:" "},
            {settlement:"אבו קורינאת",council:" "},
            {settlement:"אבו קורינאת",council:"נווה מדבר"},
            {settlement:"אבו רובייעה",council:" "},
            {settlement:"אבו רוקייק",council:" "},
            {settlement:"אבו תלול",council:"נווה מדבר"},
            {settlement:"אבטין",council:"זבולון"},
            {settlement:"אבטליון",council:"משגב"},
            {settlement:"אביאל",council:"אלונה"},
            {settlement:"אביבים",council:"מרום הגליל"},
            {settlement:"אביגדור",council:"באר טוביה"},
            {settlement:"אביחיל",council:"עמק חפר"},
            {settlement:"אביטל",council:"הגלבוע"},
            {settlement:"אביעזר",council:"מטה יהודה"},
            {settlement:"אבירים",council:"מעלה יוסף"},
            {settlement:"אבן יהודה",council:"לב השרון"},
            {settlement:"אבן מנחם",council:"מעלה יוסף"},
            {settlement:"אבן ספיר",council:"מטה יהודה"},
            {settlement:"אבן שמואל",council:"שפיר"},
            {settlement:"אבני איתן",council:"גולן"},
            {settlement:"אבני חפץ",council:"שומרון"},
            {settlement:"אבנת",council:"מגילות ים המלח"},
            {settlement:"אבשלום",council:"אשכול"},
            {settlement:"אדורה",council:"הר חברון"},
            {settlement:"אדירים",council:"הגלבוע"},
            {settlement:"אדמית",council:"מטה אשר"},
            {settlement:"אדרת",council:"מטה יהודה"},
            {settlement:"אודים",council:"חוף השרון"},
            {settlement:"אודם",council:"גולן"},
            {settlement:"אוהד",council:"אשכול"},
            {settlement:"אום אל פחם",council:"מגידו"},
            {settlement:"אום אל קוטוף",council:"מנשה"},
            {settlement:"אום בטין",council:"אל קסום"},
            {settlement:"אומן",council:"הגלבוע"},
            {settlement:"אומץ",council:"עמק חפר"},
            {settlement:"אופקים",council:"מרחבים"},
            {settlement:"אור הגנוז",council:"מרום הגליל"},
            {settlement:"אור הנר",council:"שער הנגב"},
            {settlement:"אור יהודה",council:" "},
            {settlement:"אור עקיבא",council:"חוף הכרמל"},
            {settlement:"אורה",council:"מטה יהודה"},
            {settlement:"אורות",council:"באר טוביה"},
            {settlement:"אורטל",council:"גולן"},
            {settlement:"אורים",council:"אשכול"},
            {settlement:"אורנים",council:"זבולון"},
            {settlement:"אורנית",council:"דרום השרון"},
            {settlement:"אושה",council:"זבולון"},
            {settlement:"אזור",council:"עמק לוד"},
            {settlement:"אחווה",council:"באר טוביה"},
            {settlement:"אחוזם",council:"לכיש"},
            {settlement:"אחוזת ברק",council:"עמק יזרעאל"},
            {settlement:"אחיהוד",council:"מטה אשר"},
            {settlement:"אחיטוב",council:"עמק חפר"},
            {settlement:"אחיסמך",council:"חבל מודיעין"},
            {settlement:"אחיעזר",council:"עמק לוד"},
            {settlement:"אטרש",council:" "},
            {settlement:"איבים",council:"שער הנגב"},
            {settlement:"אייל",council:"דרום השרון"},
            {settlement:"איילת השחר",council:"הגליל העליון"},
            {settlement:"אילון",council:"מטה אשר"},
            {settlement:"אילות",council:"חבל אילות"},
            {settlement:"אילנייה",council:"הגליל התחתון"},
            {settlement:"אילת",council:"חבל אילות"},
            {settlement:"אירוס",council:"גן רווה"},
            {settlement:"איתמר",council:"שומרון"},
            {settlement:"איתן",council:"שפיר"},
            {settlement:"איתנים",council:"מטה יהודה"},
            {settlement:"אכסאל",council:"עמק יזרעאל"},
            {settlement:"אל עריאן",council:"מנשה"},
            {settlement:"אל סייד",council:"אל קסום"},
            {settlement:"אלומה",council:"שפיר"},
            {settlement:"אלומות",council:"עמק הירדן"},
            {settlement:"אלון הגליל",council:"עמק יזרעאל"},
            {settlement:"אלון מורה",council:"שומרון"},
            {settlement:"אלון שבות",council:"גוש עציון"},
            {settlement:"אלוני אבא",council:"עמק יזרעאל"},
            {settlement:"אלוני הבשן",council:"גולן"},
            {settlement:"אלוני יצחק",council:"מנשה"},
            {settlement:"אלונים",council:"עמק יזרעאל"},
            {settlement:"אליעד",council:"גולן"},
            {settlement:"אליאב",council:"לכיש"},
            {settlement:"אליכין",council:"מנשה"},
            {settlement:"אליפז",council:"חבל אילות"},
            {settlement:"אליפלט",council:"מבואות החרמון"},
            {settlement:"אליקים",council:"מגידו"},
            {settlement:"אלישיב",council:"עמק חפר"},
            {settlement:"אלישמע",council:"דרום השרון"},
            {settlement:"אלמגור",council:"עמק הירדן"},
            {settlement:"אלמוג",council:"מגילות ים המלח"},
            {settlement:"אלעד",council:"דרום השרון"},
            {settlement:"אל עזי",council:"יואב"},
            {settlement:"אלעזר",council:"גוש עציון"},
            {settlement:"אל עריאן",council:"מנשה"},
            {settlement:"אלפי מנשה",council:"דרום השרון"},
            {settlement:"אלקוש",council:"מעלה יוסף"},
            {settlement:"אלקנה",council:"שומרון"},
            {settlement:"אל רום",council:"גולן"},
            {settlement:"אמונים",council:"באר טוביה"},
            {settlement:"אמירים",council:"מרום הגליל"},
            {settlement:"אמנון",council:"מבואות החרמון"},
            {settlement:"אמציה",council:"לכיש"},
            {settlement:"אניעם",council:"גולן"},
            {settlement:"אסד",council:" "},
            {settlement:"אספר",council:"גוש עציון"},
            {settlement:"אעבלין",council:"אל-בטוף"},
            {settlement:"אעצם",council:" "},
            {settlement:"אפיניש",council:" "},
            {settlement:"אפיק",council:"גולן"},
            {settlement:"אפיקים",council:"עמק הירדן"},
            {settlement:"אפק",council:"מטה אשר"},
            {settlement:"אפרת",council:"גוש עציון"},
            {settlement:"ארבל",council:"הגליל התחתון"},
            {settlement:"ארגמן",council:"ערבות הירדן"},
            {settlement:"ארז",council:"שער הנגב"},
            {settlement:"אריאל",council:"דרום השרון"},
            {settlement:"ארסוף",council:"חוף השרון"},
            {settlement:"אשבול",council:"מרחבים"},
            {settlement:"אשבל",council:"משגב"},
            {settlement:"אשדוד",council:"באר טוביה"},
            {settlement:"אשדות יעקב איחוד",council:"עמק הירדן"},
            {settlement:"אשדות יעקב מאוחד",council:"עמק הירדן"},
            {settlement:"אשחר",council:"משגב"},
            {settlement:"אשכולות",council:"הר חברון"},
            {settlement:"אשל הנשיא",council:"מרחבים"},
            {settlement:"אשלים",council:"רמת נגב"},
            {settlement:"אשקלון",council:"חוף אשקלון"},
            {settlement:"אשרת",council:"מטה אשר"},
            {settlement:"אשתאול",council:"מטה יהודה"},
            {settlement:"אתגר",council:"משגב"},
            {settlement:"באקה אל גרביה",council:"מנשה"},
            {settlement:"באר אורה",council:"חבל אילות"},
            {settlement:"באר גנים",council:"חוף אשקלון"},
            {settlement:"באר טוביה",council:"באר טוביה"},
            {settlement:"באר יעקב",council:"עמק לוד"},
            {settlement:"באר מילכה",council:"רמת נגב"},
            {settlement:"באר שבע",council:"בני שמעון"},
            {settlement:"בארות יצחק",council:"חבל מודיעין"},
            {settlement:"בארותיים",council:"עמק חפר"},
            {settlement:"בארי",council:"אשכול"},
            {settlement:"בוסתן הגליל",council:"מטה אשר"},
            {settlement:"בועיינה נוגידאת",council:"אל-בטוף"},
            {settlement:"בוקעאתא",council:"גולן"},
            {settlement:"בורגתה",council:"עמק חפר"},
            {settlement:"בחן",council:"עמק חפר"},
            {settlement:"בטחה",council:"מרחבים"},
            {settlement:"ביצרון",council:"באר טוביה"},
            {settlement:"ביר אל מכסור",council:"אל-בטוף"},
            {settlement:"ביר הדאג",council:"נווה מדבר"},
            {settlement:"בירייה",council:"מרום הגליל"},
            {settlement:"בית אורן",council:"חוף הכרמל"},
            {settlement:"בית אל",council:"מטה יהודה"},
            {settlement:"בית אלעזרי",council:"ברנר"},
            {settlement:"בית אלפא",council:"הגלבוע"},
            {settlement:"בית אריה",council:"חבל מודיעין"},
            {settlement:"בית ברל",council:"דרום השרון"},
            {settlement:"בית גן",council:"מרום הגליל"},
            {settlement:"בית גוברין",council:"יואב"},
            {settlement:"בית גמליאל",council:"משגב"},
            {settlement:"בית דגן",council:"עמק לוד"},
            {settlement:"בית הגדי",council:"שדות נגב"},
            {settlement:"בית הלוי",council:"עמק חפר"},
            {settlement:"בית הלל",council:"מבואות החרמון"},
            {settlement:"בית העמק",council:"מטה אשר"},
            {settlement:"בית הערבה",council:"מגילות ים המלח"},
            {settlement:"בית השיטה",council:"הגלבוע"},
            {settlement:"בית זיד",council:"עמק יזרעאל"},
            {settlement:"בית זית",council:"מטה יהודה"},
            {settlement:"בית זרע",council:"עמק הירדן"},
            {settlement:"בית חולים פוריה",council:"עמק הירדן"},
            {settlement:"בית חורון",council:"מטה בנימין"},
            {settlement:"בית חירות",council:"עמק חפר"},
            {settlement:"בית חלקיה",council:"נחל שורק"},
            {settlement:"בית חנן",council:"גן רווה"},
            {settlement:"בית חנניה",council:"חוף הכרמל"},
            {settlement:"בית חשמונאי",council:"גזר"},
            {settlement:"בית יהושע",council:"חוף השרון"},
            {settlement:"בית יוסף",council:"עמק המעיינות"},
            {settlement:"בית ינאי",council:"עמק חפר"},
            {settlement:"בית יצחק שער חפר",council:"עמק חפר"},
            {settlement:"בית לחם הגלילית",council:"עמק יזרעאל"},
            {settlement:"בית מאיר",council:"מטה יהודה"},
            {settlement:"בית נחמיה",council:"חבל מודיעין"},
            {settlement:"בית ניר",council:"יואב"},
            {settlement:"בית נקופה",council:"מטה יהודה"},
            {settlement:"בית עובד",council:"גן רווה"},
            {settlement:"בית עוזיאל",council:"גזר"},
            {settlement:"בית עזרא",council:"באר טוביה"},
            {settlement:"בית עריף",council:"חבל מודיעין"},
            {settlement:"בית צבי",council:"חוף הכרמל"},
            {settlement:"בית קמה",council:"בני שמעון"},
            {settlement:"בית קשת",council:"הגליל התחתון"},
            {settlement:"בית רבן",council:"חבל יבנה"},
            {settlement:"בית רימון",council:"הגליל התחתון"},
            {settlement:"בית שאן",council:"עמק המעיינות"},
            {settlement:"בית שמש",council:"מטה יהודה"},
            {settlement:"בית שערים",council:"עמק יזרעאל"},
            {settlement:"בית שקמה",council:"חוף אשקלון"},
            {settlement:"ביתן אהרן",council:"עמק חפר"},
            {settlement:"ביתר עילית",council:"גוש עציון"},
            {settlement:"בלפוריה",council:"עמק יזרעאל"},
            {settlement:"בן זכאי",council:"חבל יבנה"},
            {settlement:"בן עמי",council:"מטה אשר"},
            {settlement:"בן שמן כפר נוער",council:"חבל מודיעין"},
            {settlement:"בן שמן מושב",council:"חבל מודיעין"},
            {settlement:"בני ברק",council:"דרום השרון"},
            {settlement:"בני דקלים",council:"לכיש"},
            {settlement:"בני דרום",council:"חבל יבנה"},
            {settlement:"בני דרור",council:"לב השרון"},
            {settlement:"בני יהודה",council:"גולן"},
            {settlement:"בני נצרים",council:"אשכול"},
            {settlement:"בני עטרות",council:"חבל מודיעין"},
            {settlement:"בני עיש",council:"נחל שורק"},
            {settlement:"בני ציון",council:"חוף השרון"},
            {settlement:"בני ראם",council:"נחל שורק"},
            {settlement:"בניה",council:"ברנר"},
            {settlement:"בנימינה",council:"חוף הכרמל"},
            {settlement:"בסמה",council:"מנשה"},
            {settlement:"בסמת טבעון",council:"עמק יזרעאל"},
            {settlement:"בענה",council:"משגב"},
            {settlement:"בצרה",council:"חוף השרון"},
            {settlement:"בצת",council:"מטה אשר"},
            {settlement:"בקוע",council:"מטה יהודה"},
            {settlement:"בקעות",council:"ערבות הירדן"},
            {settlement:"בר גיורא",council:"מטה יהודה"},
            {settlement:"בר יוחאי",council:"מרום הגליל"},
            {settlement:"ברוכין",council:"שומרון"},
            {settlement:"ברור חיל",council:"שער הנגב"},
            {settlement:"ברוש",council:"בני שמעון"},
            {settlement:"ברכה",council:"שומרון"},
            {settlement:"ברכיה",council:"חוף אשקלון"},
            {settlement:"ברעם",council:"הגליל העליון"},
            {settlement:"ברק",council:"הגלבוע"},
            {settlement:"ברקאי",council:"מנשה"},
            {settlement:"ברקן",council:"שומרון"},
            {settlement:"ברקת",council:"חבל מודיעין"},
            {settlement:"בת הדר",council:"חוף אשקלון"},
            {settlement:"בת חן",council:"עמק חפר"},
            {settlement:"בת חפר",council:"עמק חפר"},
            {settlement:"בת חצור",council:"באר טוביה"},
            {settlement:"בת ים",council:"עמק לוד"},
            {settlement:"בת עין",council:"גוש עציון"},
            {settlement:"בת שלמה",council:"חוף הכרמל"},
            {settlement:"גדיידה מכר",council:"משגב"},
            {settlement:"גוליס",council:"משגב"},
            {settlement:"גלגוליה",council:"דרום השרון"},
            {settlement:"גנאביב ",council:""},
            {settlement:"גסר א זרקא",council:"חוף הכרמל"},
            {settlement:"גת",council:"מנשה"},
            {settlement:"גאולי תימן",council:"עמק חפר"},
            {settlement:"גאולים",council:"לב השרון"},
            {settlement:"גאליה",council:"גן רווה"},
            {settlement:"גבולות",council:"אשכול"},
            {settlement:"גבים",council:"שער הנגב"},
            {settlement:"גבע",council:"הגלבוע"},
            {settlement:"גבע בנימין",council:"מטה בנימין"},
            {settlement:"גבע כרמל",council:"חוף הכרמל"},
            {settlement:"גבעולים",council:"שדות נגב"},
            {settlement:"גבעון החדשה",council:"מטה בנימין"},
            {settlement:"גבעות בר",council:"בני שמעון"},
            {settlement:"גבעת אבני",council:"הגליל התחתון"},
            {settlement:"גבעת אלה",council:"עמק יזרעאל"},
            {settlement:"גבעת ברנר",council:"ברנר"},
            {settlement:"גבעת השלושה",council:"דרום השרון"},
            {settlement:"גבעת זאב",council:"מטה יהודה"},
            {settlement:"גבעת חן",council:"דרום השרון"},
            {settlement:"גבעת חביבה",council:"מנשה"},
            {settlement:"גבעת חיים איחוד",council:"עמק חפר"},
            {settlement:"גבעת חיים מאוחד",council:"עמק חפר"},
            {settlement:"גבעת חן",council:"דרום השרון"},
            {settlement:"גבעת יואב",council:"גולן"},
            {settlement:"גבעת יערים",council:"מטה יהודה"},
            {settlement:"גבעת ישעיהו",council:"מטה יהודה"},
            {settlement:"גבעת כח",council:"חבל מודיעין"},
            {settlement:"גבעת נילי",council:"אלונה"},
            {settlement:"גבעת עדה",council:"חוף הכרמל"},
            {settlement:"גבעת עוז",council:"מגידו"},
            {settlement:"גבעת שמואל",council:"דרום השרון"},
            {settlement:"גבעת שמש",council:"מטה יהודה"},
            {settlement:"גבעת שפירא",council:"עמק חפר"},
            {settlement:"גבעתי",council:"באר טוביה"},
            {settlement:"גבעתיים",council:"דרום השרון"},
            {settlement:"גברעם",council:"חוף אשקלון"},
            {settlement:"גבת",council:"עמק יזרעאל"},
            {settlement:"גדות",council:"הגליל העליון"},
            {settlement:"גדיש",council:"הגלבוע"},
            {settlement:"גדעונה",council:"הגלבוע"},
            {settlement:"גדרה",council:"נחל שורק"},
            {settlement:"גוליס",council:"מטה אשר"},
            {settlement:"גונן",council:"הגליל העליון"},
            {settlement:"גורן",council:"מעלה יוסף"},
            {settlement:"גורנות הגליל",council:"מעלה יוסף"},
            {settlement:"גזית",council:"עמק יזרעאל"},
            {settlement:"גזר",council:"גזר"},
            {settlement:"גיאה",council:"חוף אשקלון"},
            {settlement:"גיבתון",council:"ברנר"},
            {settlement:"גיזו",council:"מטה יהודה"},
            {settlement:"גילון",council:"משגב"},
            {settlement:"גילת",council:"מרחבים"},
            {settlement:"גינוסר",council:"עמק הירדן"},
            {settlement:"גיניגר",council:"עמק יזרעאל"},
            {settlement:"גינתון",council:"חבל מודיעין"},
            {settlement:"גיתה",council:"מעלה יוסף"},
            {settlement:"גיתית",council:"ערבות הירדן"},
            {settlement:"גלאון",council:"יואב"},
            {settlement:"גלגוליה",council:"דרום השרון"},
            {settlement:"גלגל",council:"ערבות הירדן"},
            {settlement:"גליל ים",council:"חוף השרון"},
            {settlement:"גלעד אבן יצחק",council:"מגידו"},
            {settlement:"גמזו",council:"חבל מודיעין"},
            {settlement:"גן הדרום",council:"גדרות"},
            {settlement:"גן השומרון",council:"מנשה"},
            {settlement:"גן חיים",council:"דרום השרון"},
            {settlement:"גן יאשיה",council:"עמק חפר"},
            {settlement:"גן יבנה",council:"חבל יבנה"},
            {settlement:"גן נר",council:"הגלבוע"},
            {settlement:"גן שורק",council:"גן רווה"},
            {settlement:"גן שלמה",council:"ברנר"},
            {settlement:"גן שמואל",council:"מנשה"},
            {settlement:"גנות",council:"עמק לוד"},
            {settlement:"גנות הדר",council:"לב השרון"},
            {settlement:"גני הדר",council:"גזר"},
            {settlement:"גני טל",council:"נחל שורק"},
            {settlement:"גני יוחנן",council:"גזר"},
            {settlement:"גני מודיעין",council:"מטה בנימין"},
            {settlement:"גני עם",council:"דרום השרון"},
            {settlement:"גני תקווה",council:"דרום השרון"},
            {settlement:"גסר א זרקא",council:"חוף הכרמל"},
            {settlement:"געש",council:"חוף השרון"},
            {settlement:"געתון",council:"מטה אשר"},
            {settlement:"גפן",council:"מטה יהודה"},
            {settlement:"גרופית",council:"חבל אילות"},
            {settlement:"גיש גוש חלב",council:"מרום הגליל"},
            {settlement:"גשור",council:"גולן"},
            {settlement:"גשר",council:"עמק המעיינות"},
            {settlement:"גשר הזיו",council:"מטה אשר"},
            {settlement:"גת",council:"מנשה"},
            {settlement:"גת קיבוץ",council:"יואב"},
            {settlement:"גת רימון",council:"דרום השרון"},
            {settlement:"דאלית אל כרמל",council:"זבולון"},
            {settlement:"דבורה",council:"הגלבוע"},
            {settlement:"דבורייה",council:"עמק יזרעאל"},
            {settlement:"דבירה",council:"בני שמעון"},
            {settlement:"דברת",council:"עמק יזרעאל"},
            {settlement:"דגניה א",council:"עמק הירדן"},
            {settlement:"דגניה ב",council:"עמק הירדן"},
            {settlement:"דובב",council:"מרום הגליל"},
            {settlement:"דולב",council:"מטה בנימין"},
            {settlement:"דור",council:"חוף הכרמל"},
            {settlement:"דורות",council:"שער הנגב"},
            {settlement:"דחי",council:"בוסתאן אל-מרג"},
            {settlement:"דייר אל אסד",council:"משגב"},
            {settlement:"דייר חנא",council:"משגב"},
            {settlement:"דייר ראפאת",council:"מטה יהודה"},
            {settlement:"דימונה",council:"רמת נגב"},
            {settlement:"דישון",council:"מבואות החרמון"},
            {settlement:"דלייה",council:"מגידו"},
            {settlement:"דלתון",council:"מרום הגליל"},
            {settlement:"דמיידה",council:"משגב"},
            {settlement:"דן",council:"הגליל העליון"},
            {settlement:"דפנה",council:"הגליל העליון"},
            {settlement:"דקל",council:"אשכול"},
            {settlement:"דריגאת",council:"אל קסום"},
            {settlement:"האון",council:"עמק הירדן"},
            {settlement:"הבונים",council:"חוף הכרמל"},
            {settlement:"הגושרים",council:"הגליל העליון"},
            {settlement:"הדר עם",council:"עמק חפר"},
            {settlement:"הוד השרון",council:"דרום השרון"},
            {settlement:"הודיות",council:"הגליל התחתון"},
            {settlement:"הודייה",council:"חוף אשקלון"},
            {settlement:"הוואשלה",council:" "},
            {settlement:"הוזייל",council:" "},
            {settlement:"הושעיה",council:"עמק יזרעאל"},
            {settlement:"הזורע",council:"מגידו"},
            {settlement:"הזורעים",council:"הגליל התחתון"},
            {settlement:"החותרים",council:"חוף הכרמל"},
            {settlement:"היוגב",council:"עמק יזרעאל"},
            {settlement:"הילה",council:"מעלה יוסף"},
            {settlement:"המעפיל",council:"עמק חפר"},
            {settlement:"הסוללים",council:"עמק יזרעאל"},
            {settlement:"העוגן",council:"עמק חפר"},
            {settlement:"הר אדר",council:"מטה יהודה"},
            {settlement:"הר גילה",council:"גוש עציון"},
            {settlement:"הר עמשא",council:"תמר"},
            {settlement:"הראל",council:"מטה יהודה"},
            {settlement:"הרדוף",council:"זבולון"},
            {settlement:"הרצליה",council:"חוף השרון"},
            {settlement:"הררית",council:"משגב"},
            {settlement:"ורד יריחו",council:"מגילות ים המלח"},
            {settlement:"ורדון",council:"יואב"},
            {settlement:"זבארגה",council:" "},
            {settlement:"זבדיאל",council:"שפיר"},
            {settlement:"זוהר",council:"לכיש"},
            {settlement:"זיקים",council:"חוף אשקלון"},
            {settlement:"זיתן",council:"עמק לוד"},
            {settlement:"זכרון יעקב",council:"חוף הכרמל"},
            {settlement:"זכריה",council:"מטה יהודה"},
            {settlement:"זמר",council:"עמק חפר"},
            {settlement:"זמרת",council:"שדות נגב"},
            {settlement:"זנוח",council:"מטה יהודה"},
            {settlement:"זרועה",council:"שדות נגב"},
            {settlement:"זרזיר",council:"עמק יזרעאל"},
            {settlement:"זרחיה",council:"שפיר"},
            {settlement:"חואלד",council:"עמק יזרעאל"},
            {settlement:"חבצלת השרון",council:"עמק חפר"},
            {settlement:"חבר",council:"הגלבוע"},
            {settlement:"חברון",council:"הר חברון"},
            {settlement:"חגור",council:"דרום השרון"},
            {settlement:"חגי",council:"הר חברון"},
            {settlement:"חגלה",council:"עמק חפר"},
            {settlement:"חד נס",council:"מבואות החרמון"},
            {settlement:"חדיד",council:"חבל מודיעין"},
            {settlement:"חדרה",council:"מנשה"},
            {settlement:"חואלד",council:"זבולון"},
            {settlement:"חוגיראת דהרה",council:"משגב"},
            {settlement:"חולדה",council:"גזר"},
            {settlement:"חולון",council:"עמק לוד"},
            {settlement:"חולית",council:"אשכול"},
            {settlement:"חולתה",council:"הגליל העליון"},
            {settlement:"חוסן",council:"מעלה יוסף"},
            {settlement:"חוסנייה",council:"משגב"},
            {settlement:"חופית",council:"עמק חפר"},
            {settlement:"חוקוק",council:"עמק הירדן"},
            {settlement:"חורה",council:" "},
            {settlement:"חורפיש",council:"מעלה יוסף"},
            {settlement:"חורשים",council:"דרום השרון"},
            {settlement:"חזון",council:"מרום הגליל"},
            {settlement:"חיבת ציון",council:"עמק חפר"},
            {settlement:"חיננית",council:"שומרון"},
            {settlement:"חיפה",council:"חוף הכרמל"},
            {settlement:"חירות",council:"לב השרון"},
            {settlement:"חלוץ",council:"משגב"},
            {settlement:"חלמיש",council:"מטה בנימין"},
            {settlement:"חלץ",council:"חוף אשקלון"},
            {settlement:"חמאם",council:"אל-בטוף"},
            {settlement:"חמד",council:"עמק לוד"},
            {settlement:"חמדיה",council:"עמק המעיינות"},
            {settlement:"חמדת",council:"ערבות הירדן"},
            {settlement:"חמרה",council:"ערבות הירדן"},
            {settlement:"חניאל",council:"עמק חפר"},
            {settlement:"חניתה",council:"מטה אשר"},
            {settlement:"חנתון",council:"עמק יזרעאל"},
            {settlement:"חספין",council:"גולן"},
            {settlement:"חפץ חיים",council:"נחל שורק"},
            {settlement:"חפצי-בה",council:"הגלבוע"},
            {settlement:"חצב",council:"באר טוביה"},
            {settlement:"חצבה",council:"הערבה התיכונה"},
            {settlement:"חצור אשדוד",council:"באר טוביה"},
            {settlement:"חצור הגלילית",council:"הגליל העליון"},
            {settlement:"חצר בארותיים",council:"עמק חפר"},
            {settlement:"חצרות חולדה",council:"גזר"},
            {settlement:"חצרות יסף",council:"מטה אשר"},
            {settlement:"חצרות כח",council:"חבל מודיעין"},
            {settlement:"חצרים",council:"בני שמעון"},
            {settlement:"חרב לאת",council:"עמק חפר"},
            {settlement:"חרוצים",council:"חוף השרון"},
            {settlement:"חריש",council:"מנשה"},
            {settlement:"חרמש",council:"שומרון"},
            {settlement:"חרשים",council:"משגב"},
            {settlement:"חשמונאים",council:"מטה בנימין"},
            {settlement:"טבריה",council:"עמק הירדן"},
            {settlement:"טובא זנגרייה",council:"הגליל העליון"},
            {settlement:"טורעאן",council:"אל-בטוף"},
            {settlement:"טייבה",council:"לב השרון"},
            {settlement:"טייבה בעמק",council:"הגלבוע"},
            {settlement:"טירה",council:"לב השרון"},
            {settlement:"טירת יהודה",council:"חבל מודיעין"},
            {settlement:"טירת כרמל",council:"חוף הכרמל"},
            {settlement:"טירת צבי",council:"עמק המעיינות"},
            {settlement:"טל אל",council:"מטה אשר"},
            {settlement:"טל שחר",council:"גזר"},
            {settlement:"טללים",council:"רמת נגב"},
            {settlement:"טלמון",council:"מטה בנימין"},
            {settlement:"טמרה",council:"אל-בטוף"},
            {settlement:"טנא",council:"הר חברון"},
            {settlement:"טפחות",council:"מרום הגליל"},
            {settlement:"יאנוח גת",council:"מטה אשר"},
            {settlement:"יבול",council:"אשכול"},
            {settlement:"יבנאל",council:"עמק הירדן"},
            {settlement:"יבנה",council:"חבל יבנה"},
            {settlement:"יגור",council:"זבולון"},
            {settlement:"יגל",council:"עמק לוד"},
            {settlement:"יד בנימין",council:"נחל שורק"},
            {settlement:"יד השמונה",council:"מטה יהודה"},
            {settlement:"יד חנה",council:"עמק חפר"},
            {settlement:"יד מרדכי",council:"חוף אשקלון"},
            {settlement:"יד נתן",council:"לכיש"},
            {settlement:"יד רמבם",council:"גזר"},
            {settlement:"ידידה",council:"מטה יהודה"},
            {settlement:"יהוד",council:"דרום השרון"},
            {settlement:"יהל",council:"חבל אילות"},
            {settlement:"יובל",council:"מבואות החרמון"},
            {settlement:"יובלים",council:"משגב"},
            {settlement:"יודפת",council:"משגב"},
            {settlement:"יונתן",council:"גולן"},
            {settlement:"יושיביה",council:"שדות נגב"},
            {settlement:"יזרעאל",council:"הגלבוע"},
            {settlement:"יחיעם",council:"מטה אשר"},
            {settlement:"יטבתה",council:"חבל אילות"},
            {settlement:"ייט",council:"ערבות הירדן"},
            {settlement:"יכיני",council:"שער הנגב"},
            {settlement:"ינוב",council:"לב השרון"},
            {settlement:"ינון",council:"באר טוביה"},
            {settlement:"יסוד המעלה",council:"מבואות החרמון"},
            {settlement:"יסודות",council:"נחל שורק"},
            {settlement:"יסעור",council:"מטה אשר"},
            {settlement:"יעד",council:"משגב"},
            {settlement:"יעל",council:"הגלבוע"},
            {settlement:"יעף",council:"לב השרון"},
            {settlement:"יערה",council:"מעלה יוסף"},
            {settlement:"יפיע",council:"אל-בטוף"},
            {settlement:"יפית",council:"ערבות הירדן"},
            {settlement:"יפעת",council:"עמק יזרעאל"},
            {settlement:"יפתח",council:"הגליל העליון"},
            {settlement:"יצהר",council:"שומרון"},
            {settlement:"יציץ",council:"גזר"},
            {settlement:"יקום",council:"חוף השרון"},
            {settlement:"יקיר",council:"שומרון"},
            {settlement:"יקנעם מושבה",council:"מגידו"},
            {settlement:"יקנעם עילית",council:"מגידו"},
            {settlement:"יראון",council:"הגליל העליון"},
            {settlement:"ירדנה",council:"עמק המעיינות"},
            {settlement:"ירוחם",council:"רמת נגב"},
            {settlement:"ירושלים",council:"מטה בנימין"},
            {settlement:"ירחיב",council:"דרום השרון"},
            {settlement:"ירכא",council:"משגב"},
            {settlement:"ירקונה",council:"דרום השרון"},
            {settlement:"ישע",council:"אשכול"},
            {settlement:"ישעי",council:"מטה יהודה"},
            {settlement:"ישרש",council:"גזר"},
            {settlement:"יתד",council:"אשכול"},
            {settlement:"יתיר",council:"בני שמעון"},
            {settlement:"כאבול",council:"אל-בטוף"},
            {settlement:"כאוכב אבו אל היגא",council:"משגב"},
            {settlement:"כברי",council:"מטה אשר"},
            {settlement:"כדורי",council:"הגליל התחתון"},
            {settlement:"כדיתה",council:"מרום הגליל"},
            {settlement:"כוכב השחר",council:"מטה בנימין"},
            {settlement:"כוכב יאיר",council:"דרום השרון"},
            {settlement:"כוכב יעקב",council:"מטה בנימין"},
            {settlement:"כוכב מיכאל",council:"חוף אשקלון"},
            {settlement:"כורזים",council:"מבואות החרמון"},
            {settlement:"כחל",council:"מבואות החרמון"},
            {settlement:"כחלה",council:"אל קסום"},
            {settlement:"כיסופים",council:"אשכול"},
            {settlement:"כישור",council:"משגב"},
            {settlement:"כליל",council:"מטה אשר"},
            {settlement:"כלנית",council:"מרום הגליל"},
            {settlement:"כמאנה",council:"משגב"},
            {settlement:"כמהין",council:"רמת נגב"},
            {settlement:"כמון",council:"משגב"},
            {settlement:"כנות",council:"באר טוביה"},
            {settlement:"כנף",council:"גולן"},
            {settlement:"כנרת מושבה",council:"עמק הירדן"},
            {settlement:"כנרת קיבוץ",council:"עמק הירדן"},
            {settlement:"כסיפה",council:"תמר"},
            {settlement:"כסלון",council:"מטה יהודה"},
            {settlement:"כסרא סמיע",council:"משגב"},
            {settlement:"כעביה טבאש חגאגרה",council:"אל-בטוף"},
            {settlement:"כפר אביב",council:"גדרות"},
            {settlement:"כפר אדומים",council:"מטה בנימין"},
            {settlement:"כפר אוריה",council:"מטה יהודה"},
            {settlement:"כפר אחים",council:"באר טוביה"},
            {settlement:"כפר ביאליק",council:"זבולון"},
            {settlement:"כפר בילו",council:"גזר"},
            {settlement:"כפר בלום",council:"הגליל העליון"},
            {settlement:"כפר בן נון",council:"גזר"},
            {settlement:"כפר ברא",council:"דרום השרון"},
            {settlement:"כפר ברוך",council:"עמק יזרעאל"},
            {settlement:"כפר גדעון",council:"עמק יזרעאל"},
            {settlement:"כפר גלים",council:"חוף הכרמל"},
            {settlement:"כפר גליקסון",council:"מנשה"},
            {settlement:"כפר גלעדי",council:"הגליל העליון"},
            {settlement:"כפר דניאל",council:"חבל מודיעין"},
            {settlement:"כפר האורנים",council:"מטה בנימין"},
            {settlement:"כפר החורש",council:"עמק יזרעאל"},
            {settlement:"כפר המכבי",council:"זבולון"},
            {settlement:"כפר הנגיד",council:"גן רווה"},
            {settlement:"כפר הנוער הדתי",council:"זבולון"},
            {settlement:"כפר הנשיא",council:"הגליל העליון"},
            {settlement:"כפר הס",council:"לב השרון"},
            {settlement:"כפר הראה",council:"עמק חפר"},
            {settlement:"כפר הריף",council:"יואב"},
            {settlement:"כפר ויתקין",council:"עמק חפר"},
            {settlement:"כפר ורבורג",council:"באר טוביה"},
            {settlement:"כפר ורדים",council:"מעלה יוסף"},
            {settlement:"כפר זוהרים",council:"מטה יהודה"},
            {settlement:"כפר זיתים",council:"הגליל התחתון"},
            {settlement:"כפר חבד",council:"עמק לוד"},
            {settlement:"כפר חושן",council:"מרום הגליל"},
            {settlement:"כפר חיטים",council:"הגליל התחתון"},
            {settlement:"כפר חיים",council:"עמק חפר"},
            {settlement:"כפר חנניה",council:"מרום הגליל"},
            {settlement:"כפר חסידים א",council:"זבולון"},
            {settlement:"כפר חסידים ב",council:"זבולון"},
            {settlement:"כפר חרוב",council:"גולן"},
            {settlement:"כפר טרומן",council:"חבל מודיעין"},
            {settlement:"כפר יאסיף",council:"מטה אשר"},
            {settlement:"כפר ידידיה",council:"עמק חפר"},
            {settlement:"כפר יהושע",council:"עמק יזרעאל"},
            {settlement:"כפר יונה",council:"לב השרון"},
            {settlement:"כפר יחזקאל",council:"הגלבוע"},
            {settlement:"כפר יעבץ",council:"לב השרון"},
            {settlement:"כפר כמא",council:" "},
            {settlement:"כפר כנא",council:"אל-בטוף"},
            {settlement:"כפר מונש",council:"עמק חפר"},
            {settlement:"כפר מימון",council:"שדות נגב"},
            {settlement:"כפר מלל",council:"דרום השרון"},
            {settlement:"כפר מנדא",council:"אל-בטוף"},
            {settlement:"כפר מנחם",council:"יואב"},
            {settlement:"כפר מסריק",council:"מטה אשר"},
            {settlement:"כפר מצר",council:"בוסתאן אל-מרג"},
            {settlement:"כפר מרדכי",council:"גדרות"},
            {settlement:"כפר נטר",council:"חוף השרון"},
            {settlement:"כפר סאלד",council:"הגליל העליון"},
            {settlement:"כפר סבא",council:"דרום השרון"},
            {settlement:"כפר סילבר",council:"חוף אשקלון"},
            {settlement:"כפר סירקין",council:"דרום השרון"},
            {settlement:"כפר עבודה",council:"לב השרון"},
            {settlement:"כפר עזה",council:"שער הנגב"},
            {settlement:"כפר עציון",council:"גוש עציון"},
            {settlement:"כפר פינס",council:"מנשה"},
            {settlement:"כפר קאסם",council:"דרום השרון"},
            {settlement:"כפר קיש",council:"הגליל התחתון"},
            {settlement:"כפר קרע",council:"מנשה"},
            {settlement:"כפר ראש הנקרה",council:"מטה אשר"},
            {settlement:"כפר רוזנואלד זרעית",council:"מעלה יוסף"},
            {settlement:"כפר רופין",council:"עמק המעיינות"},
            {settlement:"כפר רות",council:"חבל מודיעין"},
            {settlement:"כפר שמאי",council:"מרום הגליל"},
            {settlement:"כפר שמואל",council:"גזר"},
            {settlement:"כפר שמריהו",council:"חוף השרון"},
            {settlement:"כפר תבור",council:"הגליל התחתון"},
            {settlement:"כפר תפוח",council:"שומרון"},
            {settlement:"כרי דשא",council:"עמק הירדן"},
            {settlement:"כרכום",council:"מבואות החרמון"},
            {settlement:"כרם בן זמרה",council:"מרום הגליל"},
            {settlement:"כרם בן שמן",council:"חבל מודיעין"},
            {settlement:"כרם יבנה",council:"חבל יבנה"},
            {settlement:"כרם מהרל",council:"חוף הכרמל"},
            {settlement:"כרם שלום",council:"אשכול"},
            {settlement:"כרמי יוסף",council:"גזר"},
            {settlement:"כרמי צור",council:"גוש עציון"},
            {settlement:"כרמיאל",council:"משגב"},
            {settlement:"כרמייה",council:"חוף אשקלון"},
            {settlement:"כרמים",council:"בני שמעון"},
            {settlement:"כרמל",council:"הר חברון"},
            {settlement:"לבון",council:"משגב"},
            {settlement:"לביא",council:"הגליל התחתון"},
            {settlement:"לבנים",council:"מרום הגליל"},
            {settlement:"להב",council:"בני שמעון"},
            {settlement:"להבות הבשן",council:"הגליל העליון"},
            {settlement:"להבות חביבה",council:"מנשה"},
            {settlement:"להבים",council:"בני שמעון"},
            {settlement:"לוד",council:"עמק לוד"},
            {settlement:"לוזית",council:"מטה יהודה"},
            {settlement:"לוחמי הגיטאות",council:"מטה אשר"},
            {settlement:"לוטם",council:"משגב"},
            {settlement:"לוטן",council:"חבל אילות"},
            {settlement:"לימן",council:"מטה אשר"},
            {settlement:"לכיש",council:"לכיש"},
            {settlement:"לפיד",council:"חבל מודיעין"},
            {settlement:"לפידות",council:"מעלה יוסף"},
            {settlement:"לקיה",council:" "},
            {settlement:"מאור",council:"מנשה"},
            {settlement:"מאיר שפיה",council:"חוף הכרמל"},
            {settlement:"מבוא ביתר",council:"מטה יהודה"},
            {settlement:"מבוא דותן",council:"שומרון"},
            {settlement:"מבוא חורון",council:"מטה בנימין"},
            {settlement:"מבוא חמה",council:"גולן"},
            {settlement:"מבוא מודיעים",council:"חבל מודיעין"},
            {settlement:"מבואות ים",council:"עמק חפר"},
            {settlement:"מבועים",council:"מרחבים"},
            {settlement:"מבטחים",council:"אשכול"},
            {settlement:"מבקיעים",council:"חוף אשקלון"},
            {settlement:"מבשרת ציון",council:"מטה יהודה"},
            {settlement:"מגאר",council:"הגליל התחתון"},
            {settlement:"מגד אל כרום",council:"משגב"},
            {settlement:"מגדים",council:"חוף הכרמל"},
            {settlement:"מגדל",council:"הגליל התחתון"},
            {settlement:"מגדל העמק",council:"עמק יזרעאל"},
            {settlement:"מגדל עוז",council:"גוש עציון"},
            {settlement:"מגדל שמס",council:"גולן"},
            {settlement:"מגדלים",council:"שומרון"},
            {settlement:"מגידו",council:"מגידו"},
            {settlement:"מגל",council:"מנשה"},
            {settlement:"מגן",council:"אשכול"},
            {settlement:"מגן שאול",council:"הגלבוע"},
            {settlement:"מגשימים",council:"דרום השרון"},
            {settlement:"מדרך עוז",council:"מגידו"},
            {settlement:"מדרשת בן גוריון",council:"רמת נגב"},
            {settlement:"מדרשת רופין",council:"עמק חפר"},
            {settlement:"מודיעין עילית",council:"מטה בנימין"},
            {settlement:"מודיעין מכבים רעות",council:"גזר"},
            {settlement:"מולדה",council:"אל קסום"},
            {settlement:"מולדת",council:"הגלבוע"},
            {settlement:"מוצא עילית",council:"מטה יהודה"},
            {settlement:"מוקייבלה",council:"הגלבוע"},
            {settlement:"מורן",council:"משגב"},
            {settlement:"מורשת",council:"משגב"},
            {settlement:"מזור",council:"חבל מודיעין"},
            {settlement:"מזכרת בתיה",council:"גזר"},
            {settlement:"מזרע",council:"עמק יזרעאל"},
            {settlement:"מזרעה",council:"מטה אשר"},
            {settlement:"מחולה",council:"ערבות הירדן"},
            {settlement:"מחנה הילה",council:"גן רווה"},
            {settlement:"מחנה טלי",council:"רמת נגב"},
            {settlement:"מחנה יהודית",council:"עמק יזרעאל"},
            {settlement:"מחנה יוכבד",council:"חבל אילות"},
            {settlement:"מחנה יפה",council:"מרחבים"},
            {settlement:"מחנה יתיר",council:"בני שמעון"},
            {settlement:"מחנה מרים",council:"באר טוביה"},
            {settlement:"מחנה עדי",council:" "},
            {settlement:"מחנה תל נוף",council:"ברנר"},
            {settlement:"מחניים",council:"הגליל העליון"},
            {settlement:"מחסיה",council:"מטה יהודה"},
            {settlement:"מטולה",council:"הגליל העליון"},
            {settlement:"מטע",council:"מטה יהודה"},
            {settlement:"מי עמי",council:"מנשה"},
            {settlement:"מיטב",council:"הגלבוע"},
            {settlement:"מייסר",council:"מנשה"},
            {settlement:"מיצר",council:"גולן"},
            {settlement:"מירב",council:"עמק המעיינות"},
            {settlement:"מירון",council:"מרום הגליל"},
            {settlement:"מישר",council:"גדרות"},
            {settlement:"מיתר",council:"בני שמעון"},
            {settlement:"מכורה",council:"ערבות הירדן"},
            {settlement:"מכחול",council:"אל קסום"},
            {settlement:"מכמורת",council:"עמק חפר"},
            {settlement:"מכמנים",council:"משגב"},
            {settlement:"מלאה",council:"הגלבוע"},
            {settlement:"מלילות",council:"שדות נגב"},
            {settlement:"מלכייה",council:"הגליל העליון"},
            {settlement:"מלכישוע",council:"עמק המעיינות"},
            {settlement:"מנוחה",council:"לכיש"},
            {settlement:"מנוף",council:"משגב"},
            {settlement:"מנות",council:"מעלה יוסף"},
            {settlement:"מנחמיה",council:"עמק המעיינות"},
            {settlement:"מנרה",council:"הגליל העליון"},
            {settlement:"מנשית זבדה",council:"עמק יזרעאל"},
            {settlement:"מסד",council:"הגליל התחתון"},
            {settlement:"מסדה",council:"עמק הירדן"},
            {settlement:"מסילות",council:"עמק המעיינות"},
            {settlement:"מסילת ציון",council:"מטה יהודה"},
            {settlement:"מסלול",council:"מרחבים"},
            {settlement:"מסעדה",council:"גולן"},
            {settlement:"מסעודין אל עזאזמה ",council:" "},
            {settlement:"מעברות",council:"עמק חפר"},
            {settlement:"מעגלים",council:"שדות נגב"},
            {settlement:"מעגן",council:"עמק הירדן"},
            {settlement:"מעגן מיכאל",council:"חוף הכרמל"},
            {settlement:"מעוז חיים",council:"עמק המעיינות"},
            {settlement:"מעון",council:"הר חברון"},
            {settlement:"מעונה",council:"מעלה יוסף"},
            {settlement:"מעיין ברוך",council:"הגליל העליון"},
            {settlement:"מעיין צבי",council:"הגליל העליון"},
            {settlement:"מעיליא",council:"מעלה יוסף"},
            {settlement:"מעלה אדומים",council:"מטה בנימין"},
            {settlement:"מעלה אפרים",council:"ערבות הירדן"},
            {settlement:"מעלה גלבוע",council:"עמק המעיינות"},
            {settlement:"מעלה גמלא",council:"גולן"},
            {settlement:"מעלה החמישה",council:"מטה יהודה"},
            {settlement:"מעלה לבונה",council:"מטה בנימין"},
            {settlement:"מעלה מכמש",council:"מטה בנימין"},
            {settlement:"מעלה עירון",council:"מגידו"},
            {settlement:"מעלה עמוס",council:"גוש עציון"},
            {settlement:"מעלה שומרון",council:"שומרון"},
            {settlement:"מעלות תרשיחא",council:"מעלה יוסף"},
            {settlement:"מענית",council:"מנשה"},
            {settlement:"מעש",council:"דרום השרון"},
            {settlement:"מפלסים",council:"שער הנגב"},
            {settlement:"מצדות יהודה",council:"הר חברון"},
            {settlement:"מצובה",council:"מטה אשר"},
            {settlement:"מצליח",council:"גזר"},
            {settlement:"מצפה",council:"הגליל התחתון"},
            {settlement:"מצפה אביב",council:"משגב"},
            {settlement:"מצפה אילן",council:"מנשה"},
            {settlement:"מצפה יריחו",council:"מטה בנימין"},
            {settlement:"מצפה נטופה",council:"הגליל התחתון"},
            {settlement:"מצפה רמון",council:"רמת נגב"},
            {settlement:"מצפה שלם",council:"מגילות ים המלח"},
            {settlement:"מצר",council:"מנשה"},
            {settlement:"מקווה ישראל",council:"עמק לוד"},
            {settlement:"מרגליות",council:"מבואות החרמון"},
            {settlement:"מרום גולן",council:"גולן"},
            {settlement:"מרחב עם",council:"רמת נגב"},
            {settlement:"מרחביה מושב",council:"עמק יזרעאל"},
            {settlement:"מרחביה קיבוץ",council:"עמק יזרעאל"},
            {settlement:"מרכז שפירא",council:"שפיר"},
            {settlement:"משאבי שדה",council:"רמת נגב"},
            {settlement:"משגב דב",council:"גדרות"},
            {settlement:"משגב עם",council:"הגליל העליון"},
            {settlement:"משהד",council:"אל-בטוף"},
            {settlement:"משואה",council:"ערבות הירדן"},
            {settlement:"משואות יצחק",council:"שפיר"},
            {settlement:"משכיות",council:"ערבות הירדן"},
            {settlement:"משמר איילון",council:"גזר"},
            {settlement:"משמר דוד",council:"גזר"},
            {settlement:"משמר הירדן",council:"מבואות החרמון"},
            {settlement:"משמר הנגב",council:"בני שמעון"},
            {settlement:"משמר העמק",council:"מגידו"},
            {settlement:"משמר השבעה",council:"עמק לוד"},
            {settlement:"משמר השרון",council:"עמק חפר"},
            {settlement:"משמרות",council:"מנשה"},
            {settlement:"משמרת",council:"לב השרון"},
            {settlement:"משען",council:"חוף אשקלון"},
            {settlement:"מתן",council:"דרום השרון"},
            {settlement:"מתת",council:"מעלה יוסף"},
            {settlement:"מתתיהו",council:"מטה בנימין"},
            {settlement:"נאות גולן",council:"גולן"},
            {settlement:"נאות הכיכר",council:"תמר"},
            {settlement:"נאות מרדכי",council:"הגליל העליון"},
            {settlement:"נאות סמדר",council:"חבל אילות"},
            {settlement:"נאעורה",council:"הגלבוע"},
            {settlement:"נבטים",council:"בני שמעון"},
            {settlement:"נגבה",council:"יואב"},
            {settlement:"נגוהות",council:"הר חברון"},
            {settlement:"נהורה",council:"לכיש"},
            {settlement:"נהלל",council:"עמק יזרעאל"},
            {settlement:"נהרייה",council:"מטה אשר"},
            {settlement:"נוב",council:"גולן"},
            {settlement:"נוגה",council:"לכיש"},
            {settlement:"נווה",council:"אשכול"},
            {settlement:"נווה אבות",council:"מנשה"},
            {settlement:"נווה אור",council:"עמק המעיינות"},
            {settlement:"נווה אטיב",council:"גולן"},
            {settlement:"נווה אילן",council:"מטה יהודה"},
            {settlement:"נווה איתן",council:"עמק המעיינות"},
            {settlement:"נווה דניאל",council:"גוש עציון"},
            {settlement:"נווה זוהר",council:"תמר"},
            {settlement:"נווה זיו",council:"מעלה יוסף"},
            {settlement:"נווה חריף",council:"חבל אילות"},
            {settlement:"נווה ים",council:"חוף הכרמל"},
            {settlement:"נווה ימין",council:"דרום השרון"},
            {settlement:"נווה ירק",council:"דרום השרון"},
            {settlement:"נווה מבטח",council:"באר טוביה"},
            {settlement:"נווה מיכאל",council:"מטה יהודה"},
            {settlement:"נווה שלום",council:"מטה יהודה"},
            {settlement:"נועם",council:"שפיר"},
            {settlement:"נוף איילון",council:"גזר"},
            {settlement:"נופים",council:"שומרון"},
            {settlement:"נופית",council:"זבולון"},
            {settlement:"נופך",council:"חבל מודיעין"},
            {settlement:"נוקדים",council:"גוש עציון"},
            {settlement:"נורדייה",council:"לב השרון"},
            {settlement:"נורית",council:"הגלבוע"},
            {settlement:"נחושה",council:"מטה יהודה"},
            {settlement:"נחל עוז",council:"שער הנגב"},
            {settlement:"נחלה",council:"יואב"},
            {settlement:"נחליאל",council:"מטה בנימין"},
            {settlement:"נחלים",council:"חבל מודיעין"},
            {settlement:"נחם",council:"מטה יהודה"},
            {settlement:"נחף",council:"משגב"},
            {settlement:"נחשולים",council:"חוף הכרמל"},
            {settlement:"נחשון",council:"מטה יהודה"},
            {settlement:"נחשונים",council:"דרום השרון"},
            {settlement:"נטועה",council:"מעלה יוסף"},
            {settlement:"נטור",council:"גולן"},
            {settlement:"נטע",council:"לכיש"},
            {settlement:"נטעים",council:"גן רווה"},
            {settlement:"נטף",council:"מטה יהודה"},
            {settlement:"ניין",council:"בוסתאן אל-מרג"},
            {settlement:"נילי",council:"מטה בנימין"},
            {settlement:"ניצן",council:"חוף אשקלון"},
            {settlement:"ניצן ב",council:"חוף אשקלון"},
            {settlement:"ניצנה ",council:"רמת נגב"},
            {settlement:"ניצני סיני",council:"רמת נגב"},
            {settlement:"ניצני עוז",council:"לב השרון"},
            {settlement:"ניצנים",council:"חוף אשקלון"},
            {settlement:"ניר אליהו",council:"דרום השרון"},
            {settlement:"ניר בנים",council:"באר טוביה"},
            {settlement:"ניר גלים",council:"חבל יבנה"},
            {settlement:"ניר דוד תל עמל",council:"עמק המעיינות"},
            {settlement:"ניר חן",council:"לכיש"},
            {settlement:"ניר יפה",council:"הגלבוע"},
            {settlement:"ניר יצחק",council:"אשכול"},
            {settlement:"ניר ישראל",council:"חוף אשקלון"},
            {settlement:"ניר משה",council:"מרחבים"},
            {settlement:"ניר עוז",council:"אשכול"},
            {settlement:"ניר עם",council:"שער הנגב"},
            {settlement:"ניר עציון",council:"חוף הכרמל"},
            {settlement:"ניר עקיבא",council:"מרחבים"},
            {settlement:"ניר צבי",council:"עמק לוד"},
            {settlement:"נירים",council:"אשכול"},
            {settlement:"נירית",council:"דרום השרון"},
            {settlement:"נירן",council:"ערבות הירדן"},
            {settlement:"נמל תעופה בן גוריון",council:"דרום השרון"},
            {settlement:"נס הרים",council:"מטה יהודה"},
            {settlement:"נס עמים",council:"מטה אשר"},
            {settlement:"נס ציונה",council:"גן רווה"},
            {settlement:"נעורים",council:"עמק חפר"},
            {settlement:"נעלה",council:"מטה בנימין"},
            {settlement:"נעמה",council:"ערבות הירדן"},
            {settlement:"נען",council:"גזר"},
            {settlement:"נצאצרה ",council:" "},
            {settlement:"נצר חזני",council:"נחל שורק"},
            {settlement:"נצר סרני",council:"גזר"},
            {settlement:"נצרת",council:"אל-בטוף"},
            {settlement:"נצרת עילית",council:"אל-בטוף"},
            {settlement:"נשר",council:"זבולון"},
            {settlement:"נתיב הגדוד",council:"ערבות הירדן"},
            {settlement:"נתיב הלה",council:"מטה יהודה"},
            {settlement:"נתיב העשרה",council:"חוף אשקלון"},
            {settlement:"נתיב השיירה",council:"מטה אשר"},
            {settlement:"נתיבות",council:"שדות נגב"},
            {settlement:"נתניה",council:"עמק חפר"},
            {settlement:"סאגור",council:"משגב"},
            {settlement:"סאסא",council:"הגליל העליון"},
            {settlement:"סביון",council:"דרום השרון"},
            {settlement:"סגולה",council:"יואב"},
            {settlement:"סואעד חמרייה",council:"עמק יזרעאל"},
            {settlement:"סואעד כמאנה",council:"משגב"},
            {settlement:"סולם",council:"בוסתאן אל-מרג"},
            {settlement:"סוסיה",council:"הר חברון"},
            {settlement:"סופה",council:"אשכול"},
            {settlement:"סחנין",council:"משגב"},
            {settlement:"סייד ",council:" "},
            {settlement:"סלמה",council:"משגב"},
            {settlement:"סלעית",council:"שומרון"},
            {settlement:"סלפית",council:"דרום השרון"},
            {settlement:"סמר",council:"חבל אילות"},
            {settlement:"סנסנה",council:"הר חברון"},
            {settlement:"סעד",council:"שדות נגב"},
            {settlement:"סער",council:"מטה אשר"},
            {settlement:"ספיר",council:"הערבה התיכונה"},
            {settlement:"סתרייה",council:"גזר"},
            {settlement:"עגר",council:"מעלה יוסף"},
            {settlement:"עבדון",council:"מטה אשר"},
            {settlement:"עברון",council:"מטה אשר"},
            {settlement:"עגור",council:"מטה יהודה"},
            {settlement:"עדי",council:"עמק יזרעאל"},
            {settlement:"עדנים",council:"דרום השרון"},
            {settlement:"עוזה",council:"שפיר"},
            {settlement:"עוזייר",council:"אל-בטוף"},
            {settlement:"עולש",council:"עמק חפר"},
            {settlement:"עומר",council:"בני שמעון"},
            {settlement:"עופר",council:"חוף הכרמל"},
            {settlement:"עופרה",council:"מטה בנימין"},
            {settlement:"עוצם",council:"לכיש"},
            {settlement:"עוקבי בנו עוקבה ",council:" "},
            {settlement:"עזוז",council:"רמת נגב"},
            {settlement:"עזר",council:"באר טוביה"},
            {settlement:"עזריאל",council:"לב השרון"},
            {settlement:"עזריה",council:"גזר"},
            {settlement:"עזריקם",council:"באר טוביה"},
            {settlement:"עטאוונה ",council:" "},
            {settlement:"עטרת",council:"מטה בנימין"},
            {settlement:"עידן",council:"הערבה התיכונה"},
            {settlement:"עיילבון",council:"גולן"},
            {settlement:"עיינות",council:"גן רווה"},
            {settlement:"עילוט",council:"אל-בטוף"},
            {settlement:"עין איילה",council:"חוף הכרמל"},
            {settlement:"עין אל אסד",council:"מרום הגליל"},
            {settlement:"עין גב",council:"עמק הירדן"},
            {settlement:"עין גדי",council:"תמר"},
            {settlement:"עין דור",council:"עמק יזרעאל"},
            {settlement:"עין הבשור",council:"אשכול"},
            {settlement:"עין הוד",council:"חוף הכרמל"},
            {settlement:"עין החורש",council:"עמק חפר"},
            {settlement:"עין המפרץ",council:"מטה אשר"},
            {settlement:"עין הנציב",council:"עמק המעיינות"},
            {settlement:"עין העמק",council:"מגידו"},
            {settlement:"עין השופט",council:"מגידו"},
            {settlement:"עין השלושה",council:"אשכול"},
            {settlement:"עין ורד",council:"לב השרון"},
            {settlement:"עין זיוון",council:"גולן"},
            {settlement:"עין חוד",council:"חוף הכרמל"},
            {settlement:"עין חצבה",council:"תמר"},
            {settlement:"עין חרוד איחוד",council:"הגלבוע"},
            {settlement:"עין חרוד מאוחד",council:"הגלבוע"},
            {settlement:"עין יהב",council:"הערבה התיכונה"},
            {settlement:"עין יעקב",council:"מעלה יוסף"},
            {settlement:"עין כרם",council:"מטה יהודה"},
            {settlement:"עין כרמל",council:"חוף הכרמל"},
            {settlement:"עין מאהל",council:"אל-בטוף"},
            {settlement:"עין נקובא",council:"מטה יהודה"},
            {settlement:"עין עירון",council:"מנשה"},
            {settlement:"עין צורים",council:"שפיר"},
            {settlement:"עין קנייא",council:"גולן"},
            {settlement:"עין ראפה",council:"מטה יהודה"},
            {settlement:"עין שמר",council:"מנשה"},
            {settlement:"עין שריד",council:"לב השרון"},
            {settlement:"עין תמר",council:"תמר"},
            {settlement:"עינת",council:"דרום השרון"},
            {settlement:"עיר אובות",council:"הערבה התיכונה"},
            {settlement:"עכו",council:"מטה אשר"},
            {settlement:"עלומים",council:"שדות נגב"},
            {settlement:"עלי",council:"מטה בנימין"},
            {settlement:"עלי זהב",council:"שומרון"},
            {settlement:"עלמה",council:"מרום הגליל"},
            {settlement:"עלמון",council:"מטה בנימין"},
            {settlement:"עמוקה",council:"מרום הגליל"},
            {settlement:"עמינדב",council:"מטה יהודה"},
            {settlement:"עמיעד",council:"הגליל העליון"},
            {settlement:"עמיעוז",council:"אשכול"},
            {settlement:"עמיקם",council:"אלונה"},
            {settlement:"עמיר",council:"הגליל העליון"},
            {settlement:"עמנואל",council:"שומרון"},
            {settlement:"עמקה",council:"מטה אשר"},
            {settlement:"ענב",council:"שומרון"},
            {settlement:"עספיא",council:"חוף הכרמל"},
            {settlement:"עפולה",council:"הגלבוע"},
            {settlement:"עץ אפרים",council:"שומרון"},
            {settlement:"עצמון שגב",council:"משגב"},
            {settlement:"עראבה",council:"משגב"},
            {settlement:"עראמשה",council:"מטה אשר"},
            {settlement:"ערב אל נעים",council:"משגב"},
            {settlement:"ערד",council:"תמר"},
            {settlement:"ערוגות",council:"באר טוביה"},
            {settlement:"ערערה",council:"מנשה"},
            {settlement:"ערערה בנגב",council:"תמר"},
            {settlement:"עשרת",council:"גדרות"},
            {settlement:"עתלית",council:"חוף הכרמל"},
            {settlement:"עתניאל",council:"הר חברון"},
            {settlement:"פארן",council:"הערבה התיכונה"},
            {settlement:"פדואל",council:"שומרון"},
            {settlement:"פדויים",council:"מרחבים"},
            {settlement:"פדיה",council:"גזר"},
            {settlement:"פוריידיס",council:"חוף הכרמל"},
            {settlement:"פורייה כפר עבודה",council:"עמק הירדן"},
            {settlement:"פורייה נווה עובד",council:"עמק הירדן"},
            {settlement:"פורייה עילית",council:"עמק הירדן"},
            {settlement:"פורת",council:"לב השרון"},
            {settlement:"פטיש",council:"מרחבים"},
            {settlement:"פלך",council:"משגב"},
            {settlement:"פלמחים",council:"גן רווה"},
            {settlement:"פני חבר",council:"הר חברון"},
            {settlement:"פסגות",council:"מטה בנימין"},
            {settlement:"פסוטה",council:"מעלה יוסף"},
            {settlement:"פעמי תשז",council:"מרחבים"},
            {settlement:"פצאל",council:"ערבות הירדן"},
            {settlement:"פקיעין בוקייעה",council:"מעלה יוסף"},
            {settlement:"פקיעין חדשה",council:"מעלה יוסף"},
            {settlement:"פרדס חנה כרכור",council:"מנשה"},
            {settlement:"פרדסייה",council:"לב השרון"},
            {settlement:"פרוד",council:"מרום הגליל"},
            {settlement:"פרזון",council:"הגלבוע"},
            {settlement:"פרי גן",council:"אשכול"},
            {settlement:"פתח תקווה",council:"דרום השרון"},
            {settlement:"פתחיה",council:"גזר"},
            {settlement:"צאלים",council:"אשכול"},
            {settlement:"צביה",council:"משגב"},
            {settlement:"צבעון",council:"הגליל העליון"},
            {settlement:"צובה",council:"מטה יהודה"},
            {settlement:"צוחר",council:"אשכול"},
            {settlement:"צומת צמח",council:"עמק הירדן"},
            {settlement:"צומת פורדיס",council:"חוף הכרמל"},
            {settlement:"צומת הערבה",council:"תמר"},
            {settlement:"צומת הצקפוסט",council:"זבולון"},
            {settlement:"צומת בילו",council:"גזר"},
            {settlement:"צומת בית דגן",council:"גן רווה"},
            {settlement:"צמת גולני",council:"הגליל התחתון"},
            {settlement:"צומת גלילות",council:"חוף השרון"},
            {settlement:"צומת דליות",council:"גולן"},
            {settlement:"צומת הנגב",council:"רמת נגב"},
            {settlement:"צומת המוביל",council:"עמק יזרעאל"},
            {settlement:"צומת זבולון",council:"זבולון"},
            {settlement:"צומת הטייסים",council:"חבל מודיעין"},
            {settlement:"צומת כרם",council:"מטה יהודה"},
            {settlement:"צומת סגולה",council:"דרום השרון"},
            {settlement:"צומת פלוגות",council:"לכיש"},
            {settlement:"צומת צריפין",council:"עמק לוד"},
            {settlement:"צומת קמה ",council:"בני שמעון"},
            {settlement:"צומת קסם",council:"דרום השרון"},
            {settlement:"צומת ראם",council:"נחל שורק"},
            {settlement:"הטכניון",council:"חוף הכרמל"},
            {settlement:"אוניברסיטת חיפה",council:"חוף הכרמל"},
            {settlement:"אוניברסיטת תל אביב",council:"דרום השרון"},
            {settlement:"אוניברסיטת בן גוריון",council:"בני שמעון"},
            {settlement:"אוניברסיטת בר אילן",council:"דרום השרון"},
            {settlement:"אוניברסיטת אריאל",council:"דרום השרון"},
            {settlement:"אוניברסיטה העברית",council:"מטה בנימין"},
            {settlement:"מכללת תל חי",council:"הגליל העליון"},
            {settlement:"מכללת עמק הירדן",council:"עמק הירדן"},
            {settlement:"מכללת אורט בראודה",council:"משגב"},
            {settlement:"מכללת רמת גן",council:"דרום השרון"},
            {settlement:"מכלל שנקר",council:"דרום השרון"},
            {settlement:"צופייה",council:"חבל יבנה"},
            {settlement:"צופים",council:"שומרון"},
            {settlement:"צופית",council:"דרום השרון"},
            {settlement:"צופר",council:"הערבה התיכונה"},
            {settlement:"צוקי ים",council:"עמק חפר"},
            {settlement:"צוקים",council:"הערבה התיכונה"},
            {settlement:"צור הדסה",council:"מטה יהודה"},
            {settlement:"צור יצחק",council:"דרום השרון"},
            {settlement:"צור משה",council:"לב השרון"},
            {settlement:"צור נתן",council:"דרום השרון"},
            {settlement:"צוריאל",council:"מעלה יוסף"},
            {settlement:"צורית",council:"משגב"},
            {settlement:"ציפורי",council:"עמק יזרעאל"},
            {settlement:"צלפון",council:"מטה יהודה"},
            {settlement:"צנדלה",council:"הגלבוע"},
            {settlement:"צפרייה",council:"עמק לוד"},
            {settlement:"צפרירים",council:"מטה יהודה"},
            {settlement:"צפת",council:"הגליל העליון"},
            {settlement:"צרופה",council:"חוף הכרמל"},
            {settlement:"צרעה",council:"מטה יהודה"},
            {settlement:"קבועה ",council:"תמר"},
            {settlement:"קבוצת יבנה",council:"חבל יבנה"},
            {settlement:"קדומים",council:"דרום השרון"},
            {settlement:"קדימה צורן",council:"לב השרון"},
            {settlement:"קדמה",council:"יואב"},
            {settlement:"קדמת צבי",council:"גולן"},
            {settlement:"קדר",council:"גוש עציון"},
            {settlement:"קדרון",council:"ברנר"},
            {settlement:"קדרים",council:"הגליל העליון"},
            {settlement:"קודייראת א צאנע",council:" "},
            {settlement:"קוואעין",council:" "},
            {settlement:"קוממיות",council:"שפיר"},
            {settlement:"קורנית",council:"משגב"},
            {settlement:"קטורה",council:"חבל אילות"},
            {settlement:"קיסריה",council:"חוף הכרמל"},
            {settlement:"קלחים",council:"מרחבים"},
            {settlement:"קליה",council:"מגילות ים המלח"},
            {settlement:"קלנסווה",council:"לב השרון"},
            {settlement:"קלע",council:"גולן"},
            {settlement:"קציר",council:"מנשה"},
            {settlement:"קצר א סר",council:"נווה מדבר"},
            {settlement:"קצרין",council:"גולן"},
            {settlement:"קריית אונו",council:"דרום השרון"},
            {settlement:"קריית ארבע",council:"הר חברון"},
            {settlement:"קריית אתא",council:"זבולון"},
            {settlement:"קריית ביאליק",council:"זבולון"},
            {settlement:"קריית גת",council:"לכיש"},
            {settlement:"קריית טבעון",council:"זבולון"},
            {settlement:"קריית ים",council:"זבולון"},
            {settlement:"קריית יערים",council:"מטה יהודה"},
            {settlement:"קריית מוצקין",council:"זבולון"},
            {settlement:"קריית מלאכי",council:"באר טוביה"},
            {settlement:"קריית נטפים",council:"שומרון"},
            {settlement:"קריית ענבים",council:"מטה יהודה"},
            {settlement:"קריית עקרון",council:"גזר"},
            {settlement:"קריית שלמה",council:"חוף השרון"},
            {settlement:"קריית שמונה",council:"הגליל העליון"},
            {settlement:"קריית שומרון",council:"שומרון"},
            {settlement:"קשת",council:"גולן"},
            {settlement:"ראמה",council:"משגב"},
            {settlement:"ראס אל עין",council:"משגב"},
            {settlement:"ראס עלי",council:"זבולון"},
            {settlement:"ראש העין",council:"דרום השרון"},
            {settlement:"ראש פינה",council:"הגליל העליון"},
            {settlement:"ראש צורים",council:"גוש עציון"},
            {settlement:"ראשון לציון",council:"גן רווה"},
            {settlement:"רבבה",council:"שומרון"},
            {settlement:"רבדים",council:"יואב"},
            {settlement:"רביבים",council:"רמת נגב"},
            {settlement:"רביד",council:"עמק הירדן"},
            {settlement:"רגבה",council:"מטה אשר"},
            {settlement:"רגבים",council:"מנשה"},
            {settlement:"רהט",council:"בני שמעון"},
            {settlement:"רווחה",council:"שפיר"},
            {settlement:"רוויה",council:"עמק המעיינות"},
            {settlement:"רוח מדבר",council:"רמת נגב"},
            {settlement:"רוחמה",council:"שער הנגב"},
            {settlement:"רומאנה",council:"אל-בטוף"},
            {settlement:"רומת הייב",council:"אל-בטוף"},
            {settlement:"רועי",council:"ערבות הירדן"},
            {settlement:"רותם",council:"ערבות הירדן"},
            {settlement:"רחוב",council:"עמק המעיינות"},
            {settlement:"רחובות",council:"גן רווה"},
            {settlement:"רחלים",council:"שומרון"},
            {settlement:"ריחאנייה",council:"מרום הגליל"},
            {settlement:"ריחן",council:"שומרון"},
            {settlement:"ריינה",council:"אל-בטוף"},
            {settlement:"רימונים",council:"מטה בנימין"},
            {settlement:"רינתיה",council:"חבל מודיעין"},
            {settlement:"רכסים",council:"זבולון"},
            {settlement:"רם און",council:"הגלבוע"},
            {settlement:"רמות",council:"גולן"},
            {settlement:"רמות השבים",council:"דרום השרון"},
            {settlement:"רמות מאיר",council:"גזר"},
            {settlement:"רמות מנשה",council:"מגידו"},
            {settlement:"רמות נפתלי",council:"מבואות החרמון"},
            {settlement:"רמלה",council:"עמק לוד"},
            {settlement:"רמת גן",council:"דרום השרון"},
            {settlement:"רמת דוד",council:"עמק יזרעאל"},
            {settlement:"רמת הכובש",council:"דרום השרון"},
            {settlement:"רמת השופט",council:"מגידו"},
            {settlement:"רמת השרון",council:"חוף השרון"},
            {settlement:"רמת חובב",council:"רמת נגב"},
            {settlement:"רמת יוחנן",council:"זבולון"},
            {settlement:"רמת ישי",council:"עמק יזרעאל"},
            {settlement:"רמת מגשימים",council:"גולן"},
            {settlement:"רמת צבי",council:"הגלבוע"},
            {settlement:"רמת רזיאל",council:"מטה יהודה"},
            {settlement:"רמת רחל",council:"מטה יהודה"},
            {settlement:"רנן",council:"מרחבים"},
            {settlement:"רעים",council:"אשכול"},
            {settlement:"רעננה",council:"דרום השרון"},
            {settlement:"רקפת",council:"משגב"},
            {settlement:"רשפון",council:"חוף השרון"},
            {settlement:"רשפים",council:"עמק המעיינות"},
            {settlement:"רתמים",council:"רמת נגב"},
            {settlement:"שאר ישוב",council:"מבואות החרמון"},
            {settlement:"שבי ציון",council:"מטה אשר"},
            {settlement:"שבי שומרון",council:"שומרון"},
            {settlement:"שבלי אום אל גנם",council:"עמק יזרעאל"},
            {settlement:"שגב שלום",council:"בני שמעון"},
            {settlement:"שדה אילן",council:"הגליל התחתון"},
            {settlement:"שדה אליהו",council:"עמק המעיינות"},
            {settlement:"שדה אליעזר",council:"מבואות החרמון"},
            {settlement:"שדה בוקר",council:"רמת נגב"},
            {settlement:"שדה דוד",council:"לכיש"},
            {settlement:"שדה ורבורג",council:"דרום השרון"},
            {settlement:"שדה יואב",council:"יואב"},
            {settlement:"שדה יעקב",council:"עמק יזרעאל"},
            {settlement:"שדה יצחק",council:"מנשה"},
            {settlement:"שדה משה",council:"לכיש"},
            {settlement:"שדה נחום",council:"עמק המעיינות"},
            {settlement:"שדה נחמיה",council:"הגליל העליון"},
            {settlement:"שדה ניצן",council:"אשכול"},
            {settlement:"שדה עוזיהו",council:"באר טוביה"},
            {settlement:"שדה צבי",council:"מרחבים"},
            {settlement:"שדות ים",council:"חוף הכרמל"},
            {settlement:"שדות מיכה",council:"מטה יהודה"},
            {settlement:"שדי אברהם",council:"אשכול"},
            {settlement:"שדי חמד",council:"דרום השרון"},
            {settlement:"שדי תרומות",council:"עמק המעיינות"},
            {settlement:"שדמה",council:"גדרות"},
            {settlement:"שדמות דבורה",council:"הגליל התחתון"},
            {settlement:"שדמות מחולה",council:"ערבות הירדן"},
            {settlement:"שדרות",council:"שער הנגב"},
            {settlement:"שואבה",council:"מטה יהודה"},
            {settlement:"שובה",council:"שדות נגב"},
            {settlement:"שובל",council:"בני שמעון"},
            {settlement:"שוהם",council:"חבל מודיעין"},
            {settlement:"שומרה",council:"מעלה יוסף"},
            {settlement:"שומרייה",council:"בני שמעון"},
            {settlement:"שוקדה",council:"שדות נגב"},
            {settlement:"שורש",council:"מטה יהודה"},
            {settlement:"שורשים",council:"משגב"},
            {settlement:"שושנת העמקים",council:"עמק חפר"},
            {settlement:"שזור",council:"מרום הגליל"},
            {settlement:"שחר",council:"לכיש"},
            {settlement:"שחרות",council:"חבל אילות"},
            {settlement:"שיבולים",council:"שדות נגב"},
            {settlement:"שיטים",council:"חבל אילות"},
            {settlement:"שייח דנון",council:"מטה אשר"},
            {settlement:"שילה",council:"מטה בנימין"},
            {settlement:"שילת",council:"חבל מודיעין"},
            {settlement:"שכניה",council:"משגב"},
            {settlement:"שלווה",council:"שפיר"},
            {settlement:"שלווה במדבר",council:"רמת נגב"},
            {settlement:"שלוחות",council:"עמק המעיינות"},
            {settlement:"שלומי",council:"מטה אשר"},
            {settlement:"שלומית",council:"אשכול"},
            {settlement:"שמיר",council:"הר חברון"},
            {settlement:"שמעה",council:"בני שמעון"},
            {settlement:"שמרת",council:"עמק יזרעאל"},
            {settlement:"שמשית",council:"עמק יזרעאל"},
            {settlement:"שניר",council:"הגליל העליון"},
            {settlement:"שעב",council:"הגליל התחתון"},
            {settlement:"שעל",council:"גולן"},
            {settlement:"שעלבים",council:"גזר"},
            {settlement:"שער אפרים",council:"לב השרון"},
            {settlement:"שער הגולן",council:"עמק הירדן"},
            {settlement:"שער העמקים",council:"זבולון"},
            {settlement:"שער מנשה",council:"מנשה"},
            {settlement:"שערי תקווה",council:"שומרון"},
            {settlement:"שפיים",council:"חוף השרון"},
            {settlement:"שפיר",council:"שפיר"},
            {settlement:"שפר",council:"מרום הגליל"},
            {settlement:"שפרעם",council:"אל-בטוף"},
            {settlement:"שקד",council:"שומרון"},
            {settlement:"שקף",council:"לכיש"},
            {settlement:"שרונה",council:"הגליל התחתון"},
            {settlement:"שריגים לי און",council:"מטה יהודה"},
            {settlement:"שריד",council:"עמק יזרעאל"},
            {settlement:"שרשרת",council:"שדות נגב"},
            {settlement:"שתולה",council:"מעלה יוסף"},
            {settlement:"שתולים",council:"באר טוביה"},
            {settlement:"תאשור",council:"בני שמעון"},
            {settlement:"תדהר",council:"בני שמעון"},
            {settlement:"תובל",council:"משגב"},
            {settlement:"תומר",council:"ערבות הירדן"},
            {settlement:"תושייה",council:"שדות נגב"},
            {settlement:"תימורים",council:"באר טוביה"},
            {settlement:"תירוש",council:"מטה יהודה"},
            {settlement:"תל אביב יפו",council:"דרום השרון"},
            {settlement:"תל יוסף",council:"הגלבוע"},
            {settlement:"תל יצחק",council:"חוף השרון"},
            {settlement:"תל מונד",council:"לב השרון"},
            {settlement:"תל עדשים",council:"עמק יזרעאל"},
            {settlement:"תל קציר",council:"עמק הירדן"},
            {settlement:"תל שבע",council:"בני שמעון"},
            {settlement:"תל תאומים",council:"עמק המעיינות"},
            {settlement:"תלם",council:"הר חברון"},
            {settlement:"תלמי אליהו",council:"אשכול"},
            {settlement:"תלמי אלעזר",council:"מנשה"},
            {settlement:"תלמי בילו",council:"מרחבים"},
            {settlement:"תלמי יוסף",council:"אשכול"},
            {settlement:"תלמי יחיאל",council:"באר טוביה"},
            {settlement:"תלמי יפה",council:"חוף אשקלון"},
            {settlement:"תלמים",council:"לכיש"},
            {settlement:"תמרת",council:"עמק יזרעאל"},
            {settlement:"תנובות",council:"לב השרון"},
            {settlement:"תעוז",council:"מטה יהודה"},
            {settlement:"תפרח",council:"מרחבים"},
            {settlement:"תקומה",council:"שדות נגב"},
            {settlement:"תקוע",council:"גוש עציון"},
            {settlement:"תראבין א צאנע",council:"אל קסום"},
            {settlement:"תרום",council:"מטה יהודה"}];

    }
]);
